config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  post 'users/:id' => 'users#show'
  get 'home/about'=>'home#about'
  match '/about',to:'home#about',via: 'get'
  
  resources :books,only: [:new, :create, :index, :show, :destroy,:edit,:update]
  resources :users, only: [:show, :edit,:update,:index]
  patch '/books/:id',to:'books#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true,length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController  
  before_action :authenticate_user!

  def index
    @books=Book.page(params[:page])
    @user=User.find(current_user.id)
    @book=Book.new
    
  end

  def new
    @book=Book.new
  end
  
  def create
    @book = Book.new(books_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book)
    else
      
      render :new
      
    end
  end

  def show
    @book=Book.find(params[:id])
    
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def destroy
    book = Book.find(params[:id]) #データ(レコード)を1件取得
    book.destroy #データ（レコード）を削除
    redirect_to books_path #List一覧画面へリダイレクト
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(books_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end



  private
    def books_params
      params.require(:book).permit(:title, :body, :user_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
<span id="title">
  <h1>Books</h1>
</span>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td> <%= link_to "show", book_path(book) %> </td>
      <td><%= link_to "edit", edit_book_path(book) %> </td>
      <td><%= link_to "Destroy", book, method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
     
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_list.html.erb
<span id="title">
  <h1>Books</h1>
</span>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
      <%= link_to user_path(book.user) do %>
      <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
      <%end%></td>
      <td><%=link_to book.title, book_path(book) %></td>
      <td><%= book.body %></td>
      
     
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_new.html.erb
<div class="new">
<h1>New book</h1>
<%# ここからエラーメッセージ %>

<%= form_with model: @book, local: true do |f| %>
  
    <%# ここからエラーメッセージ %>
    <% if @book.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
  <%# ここまでエラーメッセージ %>
<!-- form_for部分 -->
   
 
    <h4>Title</h4>

    <%= f.text_field :title %>
    <% if @book.errors.include?(:title) %>
       <p style="color: red;"><%= @book.errors.full_messages_for(:title).first %>
     <% end %>
    
 
    <h4>Opinion</h4>
    <%= f.text_field :body %>
    <% if @book.errors.include?(:body) %>
      <p style="color: red;"><%=@book.errors.full_messages_for(:body).first %>
     <% end %>
    
   


        <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>

 
<% end %>
</div>

app/views/books/about.html.erb
<div class="about">
<h1>welcome to 
<span class="glyphicon glyphicon-book">
<strong>Bookers !!</strong>
</span>
</h1>
</div>

app/views/books/edit.html.erb
<div class="container">
<h1>Editing Book</h1>

<%= form_with model: @book, local: true do |f| %>
<%# ここからエラーメッセージ %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%# ここまでエラーメッセージ %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <div class="update-btn">
      <%= f.submit 'Update Book' %>    
    </div>
    <div class="showmin">
    <%= link_to "Show", book_path(@book) %>
    <div class="tate"></div>
    <a href="/books">Back</a>
    </div>
    
    
<% end %>
</div>

app/views/books/home.html.erb
<div class="container">
<h1>welcome to 
<span class="glyphicon glyphicon-book">
<strong>Bookers !!</strong>
</span>
</h1>
<p>
In<span class="glyphicon glyphicon-book">
<strong>Bookers,</strong>
</span></p>
<p>you can share and exchange your opinions , inpressions , and emotions
about various books!</p>

<a  class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">login</a>
<a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">signup</a>
</div>

app/views/books/index.html.erb
<div class="container">
<div class="row">
  <div class="col-xs-3">
    <h1>User info</h1>
   
    <%= attachment_image_tag @user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </tbody>
    </table>
       <div class="row">
   <p><%= link_to"",edit_user_path(@user),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_20149"%></p>
      
    </div>
   

    <%=render 'books/new',books: @books%>
  </div>

  <div class="col-xs-9">
    <%=render 'books/list', books: @books%>
  </div>
</div>

app/views/books/new.html.erb
<div class="new">
<h1>New book</h1>
<%# ここからエラーメッセージ %>

<%= form_with model: @book, local: true do |f| %>
  
    <%# ここからエラーメッセージ %>
    <% if @book.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
  <%# ここまでエラーメッセージ %>
<!-- form_for部分 -->
   
 
    <h4>Tilte</h4>

    <%= f.text_field :title %>
    <% if @book.errors.include?(:title) %>
       <p style="color: red;"><%= @book.errors.full_messages_for(:title).first %>
     <% end %>
    
 
    <h4>Opinion</h4>
    <%= f.text_field :body %>
    <% if @book.errors.include?(:body) %>
      <p style="color: red;"><%=@book.errors.full_messages_for(:body).first %>
     <% end %>
    
   

    <div class="btn btn-primary col-xs-12">
        <%= f.submit 'Create Book' %>
    </div>
 
<% end %>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h1>User info</h1>
   
      <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @book.user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @book.user.introduction %></th>
          </tr>
        </tbody>
      </table>
        <div class="row">
          <p><%= link_to"",edit_user_path(@book.user),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_20149"%></p>
        
        </div>
   

    <%=render 'books/new',book:@book%>
  </div>

  <div class="col-xs-9">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="users-table">
      <span id="title">
        <h1>Book detail</h1>
      </span>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          
            <tr>
              <td><%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
              <%= link_to @book.user.name,user_path(@book.user)%>
            </td>
              <td><%= link_to @book.title, book_path(@book)%></td>
              <td><%=  @book.body %></td>
              <% if @book.user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book) ,class: "btn-sm btn-success edit_book_31953"%></td>
              <td><%= link_to "Destroy", @book, method: :delete, "data-confirm" => "本当に削除しますか？" ,class: "btn-sm btn-danger destroy_book_31953"%></td>
              <%end%>
              
            
            </tr>
          
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>