config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  post 'users/:id' => 'users#show'
  get 'home/about'=>'home#about'
  match '/about',to:'home#about',via: 'get'
  
  resources :books,only: [:new, :create, :index, :show, :destroy,:edit,:update]
  resources :users, only: [:show, :edit,:update,:index]
  patch '/books/:id',to:'books#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if @book.errors.any? %>
  <div class="alert ">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <p class="navbar-brand" href="#">Bookers</p>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li >
           
            <%= link_to "Home", user_path(current_user.id),class:"glyphicon glyphicon-home home" %>
            </li>
            <li class="userss">
              
                   <a class="glyphicon glyphicon-user users" href="/users">Users</a>
            </li>
            <li >
              
              <%=  link_to "Books", books_path ,class:"glyphicon glyphicon-book books"%>
            </li>
            <li >
              <%= link_to "logout", destroy_user_session_path, method: :delete,class:"glyphicon glyphicon-log-out logout" %>
            </li>
      <% else %>
        <li class="">
          <%=  link_to "Home", root_path ,class:"glyphicon glyphicon-home home"%>
        </li>
        <li class="about">
          <a class="glyphicon glyphicon-link about" href="/home/about">About</a>
          
        </li>
        <li class="">
          <%= link_to "Sign up", new_user_registration_path,class:"glyphicon glyphicon-edit sign-up" %>
        </li>
        <li>
        <%= link_to  new_user_session_path  do %>
          <i class="glyphicon glyphicon-log-in" aria-hidden="true"></i>
          <span>login</span>
        <% end %>
      </li>
      <% end %>
        </ul>
      </div>
    </nav>

    
  </div>
  </header>
<%= yield %>
  <footer>
    <p>CopyRight Infratop.inc</p>
  </footer>
    
  </body>
</html>